### ISSUE TITLE
Question: is it possible to fake cursor position?

### ISSUE THREAD

**Issue by xzbdmw** [smjonas/live-command.nvim#36]
I think norm is much more useful than visual block, but the only regret is that some motion commands(w,e) do not display cursor positions.

**Comment by smjonas** [comment]
This would be a great enhancement, however I don't know how this can be currently implemented. For commands that only affect a single line, it would be possible to simulate a cursor. The problem is if you run a command across multiple lines: to get a cursor position, one would have to run the command for each individual line which seems quite inefficient and complicated as there would likely be many edge cases.
