### ISSUE TITLE
No range allowed when using Preview command with visual selection

### ISSUE THREAD

**Issue by jdhao** [smjonas/live-command.nvim#37]
+ I am using the latest version of this plugin.  
+ nvim version: 0.10.1
+ system: macOS

I do not have special settings, this is my config using lazy nvim:

```
  {
    "smjonas/live-command.nvim",
    -- live-command supports semantic versioning via Git tags
    -- tag = "2.*",
    config = function()
      require("live-command").setup()
    end,
  },
```

If you select a range, then use `Preview` command, I am seeing the following error:

> E481: no range allowed.

**Comment by smjonas** [comment]
This is intentional. The Preview command is meant to preview the argument passed to it exactly as provided. 

So you could do pass the range like `:Preview 5,10norm daw` instead of `:5,10Preview norm daw`. On the Reddit post, someone posted about this as well. Maybe I should Change this behavior as I agree it can be unintuitive, especially in visual mode.

**Comment by jdhao** [comment]
Thanks for the reply, my confusion comes from the usage section: https://github.com/smjonas/live-command.nvim?tab=readme-ov-file#basic-usage

There it specifically says you can use Preview command with ranges. Maybe it should be updated as well 😄

**Comment by smjonas** [comment]
Oh thanks, I'll update the documentation
